# To see the full list of configuration options, run
#
#	atuin default-config

## which style to use
## possible values: auto, full, compact
style = "compact"

word_jump_mode = "emacs"
keymap_mode = "emacs"

show_help = false
timezone = "0"