[cursor.style]
blinking = "Off"
shape = "Beam"

[font.bold]
family = "Iosevka SS01"
style = "Bold"

[font.bold_italic]
family = "Iosevka SS01"
style = "Bold Italic"

[font.italic]
family = "Iosevka SS01"
style = "Italic"

[font.normal]
family = "Iosevka SS01"
style = "Regular"

[window]
option_as_alt = "Both"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
